### ISSUE TITLE
Error on generate blade

### ISSUE THREAD

**Issue by pakuningratan** [awais-vteams/laravel-crud-generator#26]
I got this error when generate blade 
using Laravel 11

 File does not exist at path F:\LARAVEL 11\ibex\vendor\ibex\crud-generator\src\Commands/../stubs/views/blade/view-field.stub.
 
 
![ibex](https://github.com/awais-vteams/laravel-crud-generator/assets/68019361/5e3c9420-7ec1-493b-9ebe-47114ab23e13)

**Comment by awais-vteams** [comment]
It should be good now. There was a small mistake.
