### ISSUE TITLE
how can I avoid the installation of a tech stack ?

### ISSUE THREAD

**Issue by rabol** [awais-vteams/laravel-crud-generator#33]
Hi

Let's say that I have a project where I don't use or don't want Laravel Breeze or Laravel UI, how do I then avoid that ?

**Comment by awais-vteams** [comment]
@rabol As long as the application has the `layout.app` layout file, it will not install the Breez or UI package.

**Comment by rabol** [comment]
aha, ok thanks, mybe a note in the readme :)
