### ISSUE TITLE
bootstrap laravel ui

### ISSUE THREAD

**Issue by Haris-Technical-Solutions** [awais-vteams/laravel-crud-generator#36]
plz add true false check in config for 

because we some time we ahve custome code in loginController and homeController laravel/ui --auth is regenerating the files and removing old code

$this->buildLayout();

protected function buildLayout(): void
    {
        if (! (view()->exists($this->layout))) {

            $this->info('Creating Layout ...');

            $uiPackage = match ($this->options['stack']) {
                'tailwind', 'livewire', 'react', 'vue' => 'laravel/breeze',
                default => 'laravel/ui'
            };

            if (! $this->requireComposerPackages([$uiPackage], true)) {
                throw new Exception("Unable to install $uiPackage. Please install it manually");
            }

            $uiCommand = match ($this->options['stack']) {
                'tailwind' => 'php artisan breeze:install blade',
                'livewire' => 'php artisan breeze:install livewire',
                'react' => 'php artisan breeze:install react',
                'vue' => 'php artisan breeze:install vue',
                default => 'php artisan ui bootstrap --auth'
            };

            $this->runCommands([$uiCommand]);
        }
    }

**Comment by Haris-Technical-Solutions** [comment]
or i wanted to be the collaborator in this project if possible

**Comment by awais-vteams** [comment]
@Haris-Technical-Solutions Yes sure. You can collaborate and I'll review the PR.

**Comment by Haris-Technical-Solutions** [comment]
thanks, waiting for the changes and invitation to collaboration

**Comment by poynet** [comment]
> plz add true false check in config for
> 
> because we some time we ahve custome code in loginController and homeController laravel/ui --auth is regenerating the files and removing old code
> 

Hi, I've been the same problem, because my value in config/crud.php - layout => "layouts.app" does'nt exist.
Check if the parameters is good ;)

Thanks for the creator of this generator :)

**Comment by poynet** [comment]
👍 thanks

Le lun. 25 nov. 2024 à 14:15, Muhammad Awais ***@***.***> a
écrit :

**Comment by awais-vteams** [comment]
Added option for `layout = false` or `layout = null`
