### ISSUE TITLE
Api controller does not use ModelResource for all methods

### ISSUE THREAD

**Issue by adwiv** [awais-vteams/laravel-crud-generator#45]
In the generated API controller, the generated Model Resource is used only for index method. 

All other methods simply return the model object.

We should ideally use ModelResource everywhere in the API controller.

In the generated `Api\UserController.php`
```php
public function show(User $user): User
{
    return $user;
}
```

should be 

```php
public function show(User $user): User
{
    return new UserResource($user);
}
```

Similar change for other methods - store and update.

**Comment by awais-vteams** [comment]
I would be happy if you pushed the PR. I'll be checking in the next release.
