### ISSUE TITLE
Doesn't execute on PostgreSql

### ISSUE THREAD

**Issue by yeminlideveloper** [awais-vteams/laravel-crud-generator#6]
https://github.com/awais-vteams/laravel-crud-generator/blob/8470b7e9558a948374b1e3bddb9470949bbdad73/src/Commands/GeneratorCommand.php#L360

You can use ` Schema::getColumnListing($this->table)`

**Comment by awais-vteams** [comment]
@yeminlideveloper It will be good if you create the PR for that. I would be love to merge your PR. 
Make sure all custom queries will use the Schema class.

**Comment by alireza-farokhi** [comment]
i'll be happy to open a PR for That if its ok

**Comment by awais-vteams** [comment]
The above issue is fixed for PostgreSql
