### ISSUE TITLE
Oracle error

### ISSUE THREAD

**Issue by eldelassombras** [awais-vteams/laravel-crud-generator#8]
does not work with oracle via yajra package, some helpful hint.

```
Illuminate\Database\QueryException 

  Error Code    : 900
Error Message : ORA-00900: invalid SQL statement
Position      : 0
Statement     : SHOW COLUMNS FROM Tb_Caso_Especial
Bindings      : []
 (SQL: SHOW COLUMNS FROM Tb_Caso_Especial)

 at C:\laragon\www\crud\vendor\laravel\framework\src\Illuminate\Database\Connection.php:703
    699▕         // If an exception occurs when attempting to run a query, we'll format the error
    700▕         // message to include the bindings with SQL, which will make this exception a
    701▕         // lot more helpful to the developer instead of just the database's errors.
    702▕         catch (Exception $e) {
  ➜ 703▕             throw new QueryException(
    704▕                 $query, $this->prepareBindings($bindings), $e
    705▕             );
    706▕         }
    707▕     }

  1   C:\laragon\www\crud\vendor\yajra\laravel-pdo-via-oci8\src\Pdo\Oci8\Statement.php:183
      Yajra\Pdo\Oci8\Exceptions\Oci8Exception::("Error Code    : 900
Error Message : ORA-00900: invalid SQL statement
Position      : 0
Statement     : SHOW COLUMNS FROM Tb_Caso_Especial
Bindings      : []
")

  2   C:\laragon\www\crud\vendor\laravel\framework\src\Illuminate\Database\Connection.php:364
      Yajra\Pdo\Oci8\Statement::execute()

```

**Comment by arribi** [comment]
Similar problem with Sqlite3:

 Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error (SQL: SHOW COLUMNS FROM users)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:703
    699▕         // If an exception occurs when attempting to run a query, we'll format the error
    700▕         // message to include the bindings with SQL, which will make this exception a
    701▕         // lot more helpful to the developer instead of just the database's errors.
    702▕         catch (Exception $e) {
  ➜ 703▕             throw new QueryException(
    704▕                 $query, $this->prepareBindings($bindings), $e
    705▕             );
    706▕         }
    707▕     }

      +24 vendor frames 
  25  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by awais-vteams** [comment]
The above issue is fixed for Oracle.
